from enum import StrEnum


class WorkOrderStatus(StrEnum):
    """Workflow states for work order full lifecycle."""

    PROJECT_CREATED = "PROJECT_CREATED"
    WORK_ORDER_CREATED = "WORK_ORDER_CREATED"
    CONTRACT_UPLOADED = "CONTRACT_UPLOADED"
    WAIT_PRINTROOM_OFFICIAL_CONTRACT = "WAIT_PRINTROOM_OFFICIAL_CONTRACT"
    WAIT_FIRST_REVIEW_SUBMIT = "WAIT_FIRST_REVIEW_SUBMIT"
    FIRST_REVIEWING = "FIRST_REVIEWING"
    FIRST_REVIEW_REJECTED = "FIRST_REVIEW_REJECTED"
    FIRST_APPROVED_WAIT_LEADER_SUBMIT_SECOND = "FIRST_APPROVED_WAIT_LEADER_SUBMIT_SECOND"
    WAIT_SECOND_REVIEW_SUBMIT = "WAIT_SECOND_REVIEW_SUBMIT"
    SECOND_REVIEWING = "SECOND_REVIEWING"
    SECOND_REVIEW_REJECTED = "SECOND_REVIEW_REJECTED"
    SECOND_APPROVED_WAIT_LEADER_SUBMIT_THIRD = "SECOND_APPROVED_WAIT_LEADER_SUBMIT_THIRD"
    WAIT_THIRD_REVIEW_SUBMIT = "WAIT_THIRD_REVIEW_SUBMIT"
    THIRD_REVIEWING = "THIRD_REVIEWING"
    THIRD_REVIEW_REJECTED = "THIRD_REVIEW_REJECTED"
    THIRD_APPROVED_WAIT_PRINTROOM = "THIRD_APPROVED_WAIT_PRINTROOM"
    PRINTROOM_PROCESSING = "PRINTROOM_PROCESSING"
    PAPER_REPORT_ISSUED = "PAPER_REPORT_ISSUED"
